### ISSUE TITLE
Camera choice

### ISSUE THREAD

**Issue by nagem07** [VIS4ROB-lab/mav_hardware#2]
First thank you for your excellent work. I am trying to achieve similar results to yours but with a differential wheeled robot. I now have a ZED 2 camera, and have used their own 3d reconstruction application with very poor results. I am not looking into trying the same with voxblox.
However, from you paper I saw that you advised to use a camera with global shutter, while on your git the ZED 2 camera is shown as having a rolling shutter. Since, you experimented on both, does this difference in shutter cause considerable performance deterioration?

**Comment by ykompis** [comment]
I think this mostly depends on your intended scenario: rolling shutter cameras are sufficient in a lot of cases where you don't expect fast camera movement (e.g. hand-carrying the sensor) or if you are able to properly deal with the rolling shutter. 
While we saw decent performance when running ZED's own SLAM, we never managed to get any other VIO/SLAM system to work with this sensor (e.g. VINS-Fusion). Additionally, the ZED sensor is basically unusable without a GPU (you cannot even get images to ROS with the official driver and ROS wrapper) which blocked us from using it in with the Intel NUCs.
If you intend to experiment with different stereo-visual-inertial SLAM frameworks from research you will have a smoother experience with e.g. the RealSense sensors.

**Comment by nagem07** [comment]
Thank you for your answer. I am actually trying to replicate your work on a differential drive robot, I do have a top mounted ZED 2 camera connected to a Jetson Xavier, so GPU is not an issue here. I previously tried the packaged ZedFU app which claims 3d mapping capabilities, but the results are less than ideal. 
So, my other alternative here would be to follow a similar approach as yours while removing/adapting packages for my use case. Moreover, have you done any sort of calibration on the ZED as I read on the documents that none was necessary.

**Comment by lucaBartolomei** [comment]
I think that the ZED camera was internally calibrated, so we did not have to do that (@ykompis please correct me if I am wrong).

**Comment by lucaBartolomei** [comment]
I think we can close this issue - feel free to re-open in case you have other questions.
